### ISSUE TITLE
Improve specific data contract page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#235]
# Issue
We need a better page view for specific data contract page

# Possible solution

**Comment by thephez** [comment]
Hey, I just had an idea when looking at the [Data Contracts page](https://platform-explorer.com/dataContracts). Currently there are names assigned to the system contracts, but there's not a way to name other contracts (via DPNS, etc.) currently. 

We could just create a small data contract that define "aliases" for contracts. For example, it could just contain fields for the contract ID and a contract name. There's not a good way to prevent people from creating aliases for contracts that aren't their own, but it could be cross-referenced so that only "alias" documents owned by the actual contract owner identity were "official".

![image](https://github.com/user-attachments/assets/0102c358-cd94-4799-9c19-f00e955bb9a7)

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Data Contracts - Documents](https://github.com/user-attachments/assets/00e161cc-dd3b-4b76-b2d8-4fece02a91ac)
![Platform Explorer - Data Contracts - Transactions](https://github.com/user-attachments/assets/8d9f6d39-e229-4624-9b37-fbd6b86f788b)
![Platform Explorer - Data Contracts - schema](https://github.com/user-attachments/assets/05ca470e-06b4-47eb-b037-48dab5f3ff7e)
Figma link: https://www.figma.com/design/jS9Vhsc4CcAc4CbYhzbr99/Platform-Explorer-%E2%80%94-Specific-Contract-page?m=auto&t=r4NM7i04I9ASb3Pf-6
